image: registry.gitlab.com/hybrix/hybrixd/base-images/build-image:stable

stages:
 - dist

dist:
  stage: dist
  script:
    - sh ./scripts/pipeline/dist.sh
  artifacts:
    paths:
    - ./*
  only:
    refs:
      - tags
