#!/bin/sh
OLDPATH="$PATH"
WHEREAMI="`pwd`"

# $HYBRIXD/node/scripts/npm  => $HYBRIXD
SCRIPTDIR="`dirname \"$0\"`"
CLI_WALLET="`cd \"$SCRIPTDIR\" && pwd`"

LIBRARIES="$CLI_WALLET/lib"
NODEINST="`which node`"

export PATH="$CLI_WALLET/node_binaries/bin:$PATH"

if [ -z "$1" ]; then
  echo ""
  echo "Welcome to the Internet of Coins cli-wallet. A command line wallet for"
  echo "checking balances and performing transactions."
  echo ""
  echo "Type:  cli-wallet --help  ... to find out how to use the wallet."
  echo ""
  exit 0
fi

cd "$CLI_WALLET" 2>&1 > /dev/null

  node "$LIBRARIES/cli-wallet.js" $@

export PATH="$OLDPATH"
cd "$WHEREAMI"
