#!/bin/sh
OLDPATH="$PATH"
REALPATH="`realpath $0`"
WHEREAMI="`dirname $REALPATH`"
LIBRARIES="`cd \"$WHEREAMI/lib\" && pwd`"
NODEINST="`which node`"
export PATH="$WHEREAMI/node_binaries/bin:$PATH"

if [ -z "$1" ]; then
  echo ""
  echo "Welcome to Internet of Coins cli-wallet. A command line wallet for"
  echo "checking balances and performing transactions."
  echo ""
  echo "Type:  cli-wallet --help  ...to find out how to use the wallet."
  echo ""
  exit 0
fi

cd "$WHEREAMI" 2>&1 > /dev/null

  node $LIBRARIES/cli-wallet.js $@

export PATH="$OLDPATH"
cd - 2>&1 > /dev/null
