#!/bin/sh
OLDPATH="$PATH"
WHEREAMI="`pwd`"

# $HYBRIXD/node/scripts/npm  => $HYBRIXD
SCRIPTDIR="`dirname \"$0\"`"
CLI_WALLET="`cd \"$SCRIPTDIR\" && pwd`"

LIBRARIES="$CLI_WALLET/lib"

export PATH="$CLI_WALLET/node_binaries/bin:$PATH"
NODEINST="`which node`"

if [ -z "$NODEINST" ]; then
  echo ""
  echo "No version of NodeJS found, please install NodeJS version 8.12 or higher"
  echo ""
  exit 1
fi

if [ -z "$1" ]; then
  echo ""
  echo "Welcome to the Internet of Coins cli-wallet. A command line wallet for"
  echo "checking balances and performing transactions."
  echo ""
  echo "Type:  cli-wallet --help  ... to find out how to use the wallet."
  echo ""
  exit 0
fi

cd "$CLI_WALLET" 2>&1 > /dev/null

  node "$LIBRARIES/cli-wallet.js" $@

export PATH="$OLDPATH"
cd "$WHEREAMI"
